### ISSUE TITLE
Regarding the large repo size

### ISSUE THREAD

**Issue by hadware** [soundata/soundata#159]
I don't know if this is relevant with my reviewing role for this package, but you might want to clean up the repo and migrate .wav files from tests ans JSON from indexes to LFS : https://docs.github.com/en/repositories/working-with-files/managing-large-files/moving-a-file-in-your-repository-to-git-large-file-storage

**Comment by hagenw** [comment]
The problem regarding the JSON files will only be solved partially by using LFS, as they also need to be included in the Python package, see https://github.com/soundata/soundata/issues/155 for the proposal to separate the index from the Python package (which would also remove the files from this repository).

**Comment by guillemcortes** [comment]
Hi @hadware @hagenw, thank you for your valuable feedback. We've been investigating and it looks like the best option will be to use [Zenodo Communities](https://zenodo.org/communities) to store both indices and the resources files for the tests (.wav files, mostly) so they can be downloaded like it is done in [mirdata](https://github.com/mir-dataset-loaders/mirdata/blob/master/mirdata/datasets/acousticbrainz_genre.py#L68). This would add an extra step to the contributors since they will have to upload the files there, but we believe that is a sustainable solution. We are testing now how it would work. Do you have experience with Zenodo Communities? Can you think of any issues we might be overlooking? Thanks again!

**Comment by hagenw** [comment]
I think regarding the files needed for testing, I don't see an issue with using LFS and store the files inside this repo.
For the indices, it would indeed be better if they are hosted on a server from which they can be downloaded on the fly. Of course, there are not so many great and free options available for this. I have used Zenodo for this, but it could also lead to some problems, compare https://github.com/sigsep/open-unmix-pytorch/issues/138. I don't have experience with Zenodo Communities, but yes, it sounds like a possible solution.

**Comment by hagenw** [comment]
In the documentation, there seems to be already an example for hosting an index on Zenodo: https://soundata.readthedocs.io/en/latest/source/contributing.html#working-with-remote-indexes

**Comment by nkundiushuti** [comment]
I think we excluded LFS because of the size limitation (2GB per repo?). in the other repo (mirdata) we had issues with some very large indexes. to sum up, it's not sustainable to store them on LFS and zenodo is a better option.

**Comment by faroit** [comment]
Zenodo can be really slow from time to time. So if you rely on these files for unit tests I would advise against it. 

Can't files be compressed and made into the free LFS limits?

**Comment by guillemcortes** [comment]
Hi @faroit , I've just mention it on the [soundata JOSS review issue](https://github.com/openjournals/joss-reviews/issues/6634) but we think that a good compromise is to host the full indexes in zenodo and have a "sample indexes" for testing in the repo, similarly to the test audio and metadata files that we already have.

**Comment by guillemcortes** [comment]
Closing this since it has been addressed in #169
