### ISSUE TITLE
Adding FSD50K dataset

### ISSUE THREAD

**Issue by genisplaja** [soundata/soundata#32]
Hello everyone,

I am implementing a loader for the [FSD50K dataset](https://zenodo.org/record/4060432#.YE98vbRKi3I). Looking forward to contributing to `soundata`!!

**Comment by justinsalamon** [comment]
Awesome! Great to have you on board @genisplaja !

Please
* Develop on a new branch, e.g. `genisplaja/fsd50k`
* Open a PR as soon as you've made some commits, so that we can use the PR's conversation tab for comments/discussion. Please don't wait until the loader is ready before opening the PR
* Please use the [new loader template](https://github.com/soundata/soundata/blob/master/.github/PULL_REQUEST_TEMPLATE/new_loader.md) to populate the first comment in your PR and use the checklist to make sure all the necessary components have been implemented.

Let us know if you have any questions about the process, thanks!

**Comment by justinsalamon** [comment]
p.s. - you can save time (and commits) but running the unit tests locally before committing/pushing, by calling `tox -e py37`. Also please remember to run `black soundata` to ensure the code is well formatted before pushing. CC @pzinemanas

**Comment by magdalenafuentes** [comment]
Closed via #36
