### ISSUE TITLE
Update jams tests to make sense for environmental data

### ISSUE THREAD

**Issue by magdalenafuentes** [soundata/soundata#7]
Right now `test_jams_utils` is testing things such as `chords` or `notes`, we should update the tests to check things that make sense in the context of DCASE.

@justinsalamon what is the common usage of jams in this context? e.g. which name spaces besides `metadata`?

**Comment by justinsalamon** [comment]
For most datasets I think we'd end up using something like `tag_open` and whatever the equivalent is for event with start/end times and an open label vocabulary.

Scaper has it's own namespace, `scaper`, so for example datasets that were generated by Scaper in the first place like URBAN-SED and that include JAMS files in their release, could have `to_jams` directly load and return the scaper JAMS object. That's my plan for the URBAN-SED loader I'm working on right now (issue #17, PR #19 )

**Comment by justinsalamon** [comment]
Per discussion on #37 and offline, let's use the following 3 namespaces:
* If the dataset was generated via Scaper, directly return the `scaper` JAMS object (i.e. namespace = `scaper`), otherwise:
* For tags, namespace = `tag_open`
* For events, namespace = `segment_open`

In the future we may want to contribute dedicated namespaces to jams, but for now let's go with Occam's razor :)

**Comment by magdalenafuentes** [comment]
Closed via #43
